- name: os_keystone
  src: https://github.com/openstack/openstack-ansible-os_keystone
  version: origin/master
- name: apt_package_pinning
  src: https://github.com/openstack/openstack-ansible-apt_package_pinning.git
  version: origin/master
- name: galera_client
  src: https://github.com/openstack/openstack-ansible-galera_client.git
  version: origin/master
- name: plugins
  src: https://github.com/openstack/openstack-ansible-plugins.git
  version: origin/master
- name: python_venv_build
  src: https://github.com/openstack/ansible-role-python_venv_build
  version: origin/master
#- name: openstack_hosts
#  src: https://github.com/openstack/openstack-ansible-openstack_hosts
#  version: origin/master
