---

- hosts: localhost
  pre_tasks:
    - debug: var=inventory_hostname
    - debug: var=ansible_hostname
    - debug: var=venv_build_host
    - name: install python-virtualenv
      package:
        name: python-virtualenv
        state: present
    - name: install libssl-dev
      package:
        name: libssl-dev
        state: present
  roles:
    #- role: openstack_hosts
    - role: os_keystone
  vars:
      keystone_git_install_branch: "stable/rocky"
      keystone_developer_mode: true
      internal_lb_vip_address: 198.61.150.50
      public_lb_vip_address: 198.61.150.50
      keystone_galera_address: "a814c0cb01ec25cd000083501582ccc9badee967.rackspaceclouddb.com"
      keystone_galera_user: "keystone"
      keystone_container_mysql_password: "SuperSecrete"
      keystone_rabbitmq_password: "secrete"
      keystone_oslomsg_rpc_password: "secrete"
      venv_build_host: "localhost"
